### 로그인 요청

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "210@mail.com",
  "password": "1234"
}

### 인증 페이지 요청
GET http://localhost:8080/posts/foo
Content-Type: application/json
Cookie: SESSION=91a22cd6-2896-4986-9723-19d0897a6494